export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'
export const EMPTY_CART = 'EMPTY_CART'

export const PRODUCT_LIST = 'PRODUCT_LIST'
export const SET_PRODUCT_LIST = 'PRODUCT_LIST'

export const WISHLIST_ADD = 'WISHLIST_ADD'
export const WISHLIST_REMOVE = 'WISHLIST_REMOVE'

export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY'
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY'

export const ADD_RECENT_VIEW = 'ADD_RECENT_VIEW'